version: '3.7'

volumes:
  mongo-db:

networks:
  ac-node-devops:
    driver: bridge
    external: true
    name: 'ac-node-devops'

services:

  mongodb:
    image: mongo:4.2
    restart: always
    networks:
      - ac-node-devops
    environment:
      - GET_HOSTS_FROM=dns
    volumes:
      - mongo-db:/data/db
    ports:
      - 27017:27017

  ac-node:
    image: masardon/ac-node-devops:latest
    restart: always
    networks:
      - ac-node-devops
    environment:
      MONGO_URL: 'mongodb://mongodb:27017/ac_logindevops_db'
    ports:
      - 8001:3000
