apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ac-node-devops
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/ac-node-devops: "true"
  podSelector:
    matchLabels:
      io.kompose.network/ac-node-devops: "true"
