apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: mongo-db
  name: mongo-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
status: {}
